apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventory
  labels:
    app: postgres-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventory
  template:
    metadata:
      labels:
        app: postgres-inventory
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "inventory_service"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-inventory-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
spec:
  selector:
    app: postgres-inventory
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-inventory-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/postgresql-inventory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-inventory-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

