apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: 289984444906.dkr.ecr.us-east-1.amazonaws.com/ecommerce/frontend:aea8d786c883c6aae847f4683c1d4a951cd46783
          imagePullPolicy: Always
          ports:
            - containerPort: 80
