apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    collect_logs_with_filebeat: "true"
    decode_log_event_to_json_object: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        collect_logs_with_filebeat: "true"
        decode_log_event_to_json_object: "true"
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: product-service
          image: 289984444906.dkr.ecr.us-east-1.amazonaws.com/ecommerce/product-service:ccca31c5724078ad061900f7ae34b101e34312af
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: product-service
