apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    collect_logs_with_filebeat: "true"
    decode_log_event_to_json_object: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        collect_logs_with_filebeat: "true"
        decode_log_event_to_json_object: "true"
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: user-service
          image: 289984444906.dkr.ecr.us-east-1.amazonaws.com/ecommerce/user-service:ccca31c5724078ad061900f7ae34b101e34312af
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: user-service
